apiVersion: v1
kind: ConfigMap

metadata:
  name: calendario-config
  namespace: ecociente

data:
  PORT: "9800"

  DDL_AUTO: "validate"
  SHOW_SQL: "false"

  SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: "3"
  SPRING_DATASOURCE_HIKARI_MINIMUMIDLE: "1"
  SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "10000"
  SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: "60000"
  SPRING_DATASOURCE_HIKARI_MAXLIFETIME: "600000"