apiVersion: v1
kind: Secret

metadata:
  name: calendario-secret
  namespace: ecociente

type: Opaque

stringData:
  DB_URL: "jdbc:postgresql://SEU_HOST:SUA_PORTA/ecociente?sslmode=require"
  DB_USER: "SEU_USUARIO"
  DB_PASSWORD: "SUA_SENHA"
  JWT_SECRET: "SUA_CHAVE_JWT_COM_PELO_MENOS_32_CARACTERES"